export enum InstitutionType {
  PUBLIC_UNIVERSITY = 'PUBLIC_UNIVERSITY',
  PRIVATE_UNIVERSITY = 'PRIVATE_UNIVERSITY',
  HIGHER_INSTITUTE = 'HIGHER_INSTITUTE',
  VOCATIONAL_TRAINING_CENTER = 'VOCATIONAL_TRAINING_CENTER',
  ROYAL_ACADEMY = 'ROYAL_ACADEMY',
  EXECUTIVE_TRAINING_INSTITUTION = 'EXECUTIVE_TRAINING_INSTITUTION',
  POLYTECHNIC_SCHOOL = 'POLYTECHNIC_SCHOOL',
  RESEARCH_INSTITUTE = 'RESEARCH_INSTITUTE'
}
