export enum Interest {
  SCIENCES = 'SCIENCES',
  ECONOMIE = 'ECONOMIE',
  LETTRES = 'LETTRES',
  COMPUTER_SCIENCE = 'COMPUTER_SCIENCE',
  ENGINEERING = 'ENGINEERING',
  MECHANICAL_ENGINEERING = 'MECHANICAL_ENGINEERING',
  ELECTRICAL_ENGINEERING = 'ELECTRICAL_ENGINEERING',
  BUSINESS = 'BUSINESS',
  TECHNOLOGY = 'TECHNOLOGY',
  MEDICINE = 'MEDICINE',
  BUSINESS_ADMINISTRATION = 'BUSINESS_ADMINISTRATION',
  ARTS = 'ARTS'
}
