#version: '3.8'
#services:
#  app:
#    build: .
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/orientation_db
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD:
#    depends_on:
#      - db
#    networks:
#      - app-network
#
#  db:
#    image: "mysql:latest"
#    restart: always
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: orientation_db
#      MYSQL_ALLOW_EMPTY_PASSWORD: true
#    volumes:
#      - db_data:/var/lib/mysql
#    networks:
#      - app-network
#
#volumes:
#  db_data:
#
#networks:
#  app-network:
#    driver: bridge
