


version: "3.8"

services:
  filRouge:
    image: imanebahy/orientation-post-baccalauriat:latest
    ports:
      - '8081:8081'
    depends_on:
      - mysqldb
    networks:
      - my-network

  mysqldb:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: orientation_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysqldb:

networks:
  my-network:
    driver: bridge

