package com.biorbac.enums;

public enum InstitutionType {
    PUBLIC_UNIVERSITY,
    PRIVATE_UNIVERSITY,
    HIGHER_INSTITUTE,
    VOCATIONAL_TRAINING_CENTER,
    ROYAL_ACADEMY,
    EXECUTIVE_TRAINING_INSTITUTION,
    POLYTECHNIC_SCHOOL,
    RESEARCH_INSTITUTE;
}
